import type { Metadata } from "next";
import "./globals.css";
import BottomNav from "./components/BottomNav";
import { UserProvider } from "./context/userData";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
      <UserProvider> 
        {children}
        <BottomNav/>
        </UserProvider>
      </body>
    </html>
  );
}
